### ISSUE TITLE
Weather clock shows just black screen

### ISSUE THREAD

**Issue by myxor** [espruino/BangleApps#1012]
The new weather clock app just shows a black screen on my Bangle.js 1.

I have installed the weather app and it shows the current weather conditions reported by Gadgedbridge.

I will ping the creator of the clock: @jg76379

**Comment by jg76379** [comment]
Good point, I'll try to test in the emulator later.

**Comment by jg76379** [comment]
I tested in the Bangle.js 1 emulator and it is working (although it could use some formatting tweaks).

![banglejs1-emulator](https://user-images.githubusercontent.com/33971128/144877228-80654c07-8e46-4042-9d4d-5bc034f9bf4c.png)

**Comment by jg76379** [comment]
@gfwilliams looks good to me! Thanks for the optimization. It still renders the same on my Bangle 2, and looks okay on the 1 in the emulator.

I thought it might be a memory issue since the Bangle 1 has much less memory. Interesting that that extra wrapping vertical layout caused the issue, i'll watch out for that in the future.

**Comment by myxor** [comment]
Can confirm that it works on Bangle.js 1 now. Thanks!

**Comment by jg76379** [comment]
@myxor let me know if you have have any more issues or suggestions for the app!
