### ISSUE TITLE
Strange behaviour with Uint8Array buffer, and map

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1201]
function buf2hex(buffer) {
  let v = new Uint8Array(buffer);
  let m = v.map(x => x.toString(16).padStart(2, '0'));
  return m.join('');
}

const b = (new Uint8Array([4, 8, 12, 16])).buffer;
print(b);
print(buf2hex(b)); 

// should return 04080c10, instead returns 48010

**Comment by gfwilliams** [comment]
I think this is expected. Did you try running it in the browser? I think you see the same thing there.

The issue is `.map` for `Uint8Array` returns a `Uint8Array` - which can't contain strings so the string you carefully created is then turned back to a Uint8.

You can convert the Uint8Array to an array with something like this though:

```
function buf2hex(buffer) {
let v = [].slice.call(new Uint8Array(buffer));
let m = v.map(x => x.toString(16).padStart(2, '0'));
return m.join('');
}
```
