### ISSUE TITLE
Any idea why charging banks lower screen part ?

### ISSUE THREAD

**Issue by MaBecker** [espruino/BangleApps#121]
start charing, erases the lower screen section

![IMG_9897 2 2020-03-09 at 15 08 17](https://user-images.githubusercontent.com/15932646/76220504-e4c35d80-6217-11ea-96da-35cebcdf925f.png)

next clock update fixit it
 
![IMG_9897 2 2020-03-09 at 15 08 20](https://user-images.githubusercontent.com/15932646/76220496-e2f99a00-6217-11ea-9a82-f1b93a7cf5da.png)

same happens when unplug from charing

**Comment by gfwilliams** [comment]
It's because of the `Bangle.drawWidgets()` which now erases the 'widget areas' at the top and bottom of the screen. I've made some tweaks so it avoids that, but even so if someone has a widget at the bottom the screen it'll erase that corner for you.

`Bangle.drawWidgets()` wouldn't normally be called, but it *is* because now the length of the battery indicator changes depending of whether charging or not

**Comment by MaBecker** [comment]
Thanks,

> 'widget areas' at the top and **bottom** of the screen

bottom area : last 24 pixel, 

I guess that's a new nice feature that will allow more  widget - cool - thanks!

As a consequence: new app section is (0,24,240,215) - correct ?

**Comment by gfwilliams** [comment]
Yes, that's right - there has always been a bottom widget area, just nobody used it yet :)

**Comment by MaBecker** [comment]
Is it possible to specify section I like to use and if how?

**Comment by MaBecker** [comment]
https://github.com/espruino/BangleApps#graphic-areas  need's some polish ;-)

**Comment by gfwilliams** [comment]
Ahh, yes - there is info on doing widgets on https://github.com/espruino/BangleApps#widget-example now
