### ISSUE TITLE
[GPS Widget] does not work on Bangle.js 2

### ISSUE THREAD

**Issue by HilmarSt** [espruino/BangleApps#1456]
### Affected hardware version

Bangle 2

### Your firmware version

2v12

### The bug

The GPS widget does not update the status any more when (e.g.) the _GPS Info App_ is running.
I've added some <code>console.log()</code> in the draw() function of the widget, they stopped when the GPS Info App is started and start again when exited.

**Comment by hughbarney** [comment]
The gps widget has never worked particularly well as there is no Bangle.on('gpsPower') event.

The widget just looks at the state of Bangle.isGPSOn() and sets the state accordingly - but what is needed is a power change event so that the widget gets poked into redisplaying the status.   The only other way to resolve this is for every app that uses the GPS to poke the gpsWidget to tell it to redraw.  I did this in some of my apps.

In case of gpsinfo - a small change to the code would help.  It would be better if Bangle.setGPSPower(1,'app') was called before Bangle.drawWidgets().  This way when the widgets are redrawn the status of the GPS will be powered on and Bangle.isGPSOn() will return true.

I will log a request for Bangle.on('power', ) event.

**Comment by gfwilliams** [comment]
I'm just posting a response to this in #1482

**Comment by HilmarSt** [comment]
It's not only the "power" status that's not working, any status (including "fix" status) isn't updated because the <code>draw()</code> function is not called any more, probably due to a problem with <code>setInterval()</code> .

This code works well for me - if there are no objections, I will create a PR for it.
```
setInterval(()=>WIDGETS["widgps"].draw(), 2000);
WIDGETS["widgps"]={area:"tr",width:24,draw:function() {
    g.reset();
    if (Bangle.isGPSOn()) {
      const gpsObject = Bangle.getGPSFix();
      if (gpsObject && gpsObject.fix > 0) {
        g.setColor("#0F0"); // on and has fix = green
      } else {
        g.setColor("#FD0"); // on but no fix = amber
      }
    } else {
      g.setColor("#888"); // off = grey
    }
    g.drawImage(atob("GBiBAAAAAAAAAAAAAA//8B//+BgYGBgYGBgYGBgYGBgYGBgYGB//+B//+BgYGBgYGBgYGBgYGBgYGBgYGB//+A//8AAAAAAAAAAAAA=="), this.x, 2+this.y);
  }
};

```

**Comment by gfwilliams** [comment]
I think @hughbarney is working on this right now - in the issue posted above there's a much cleaner way of working out if GPS is on that doesn't require polling every few seconds

**Comment by hughbarney** [comment]
https://github.com/espruino/BangleApps/issues/1482
Has the solution to effectively get an event when the GPS is powered on.
In that issue we also discussed using on('GPS',) to get the fix into the widget.
This would remove the need for the interval timer.
I've not objection to the PR if you want to go ahead.
I'm not planning on working on this - this week now.

**Comment by gfwilliams** [comment]
Just fixed this
