### ISSUE TITLE
halign not working in nested Layout

### ISSUE THREAD

**Issue by AxelRHD** [espruino/BangleApps#1501]
### Affected hardware version

Bangle 2

### Your firmware version

2v12

### The bug

```js
var clockRunning = false;

var Layout = require("Layout");
var layout = new Layout( {
  type:"v", fillx:1, filly:1, c: [
    {type:"txt", font:"27%", label:"15:00", id:"time" },
    {type: "h", fillx:1, bgCol: '#ff0', c: [
      {type:"txt", font:"14%", label:"Q1", id:"quarter", halign: -1, col: '#fff', bgCol: '#f00' }
    ]}
  ]}, {btns: [
  {label:"Start/Stop", cb: l=>clockRunning = !clockRunning}
], lazy: true});

g.clear();
layout.render();
```

The txt-elemnt is render centered, although the parameter halign is set to '-1':
![screenshot](https://user-images.githubusercontent.com/16512322/155339849-41a3c828-f367-4103-9d6a-aaa88a34f4df.png)

Expeted behaviour:
The parent 'h'-element is expanded to full width (yellow color), so the child element should be aligned the right way.

**Comment by gfwilliams** [comment]
This is actually expected behaviour - I forget where it was now but there was big discussion about this.

The docs in the Layout module say: https://github.com/espruino/BangleApps/blob/master/modules/Layout.js#L48

> A `halign` field to set horizontal alignment WITHIN a `v` container. `-1`=left, `1`=right, `0`=center
> A `valign` field to set vertical alignment WITHIN a `h` container. `-1`=top, `1`=bottom, `0`=center

In an `h` container you might have more than one element in it, so I'm not sure what's expected to happen if you have one item with right align and one with left since they would then conflict...

I'm open to changes for the layout library but it has to be as quick as possible and lightweight, and that means not being able to handle every eventuality.
