### ISSUE TITLE
Run App Boxes Settings

### ISSUE THREAD

**Issue by Ronin0000** [espruino/BangleApps#1578]
### Affected hardware version

Bangle 2

### Your firmware version

2v12

### The bug

In the run app You should not be able to set all the boxes to nothing or set two boxes to the same option in the settings app.

**Comment by gfwilliams** [comment]
I can see if you set it to display the same thing twice, it only updates one of them - I just put in a fix for multi-selection.

However I think if you really want to select 'nothing' for all boxes then it does what you request - it doesn't appear to really break anything. At some point we've got to just draw a line and say it's not in anyone's best interests for us to be spending time trying to protect apps from people who will deliberately try and break them.

**Comment by Ronin0000** [comment]
ok!, Thanks!

**Comment by gfwilliams** [comment]
Just had to revert the fix for this as it broke Bangle.js 1 as well as 2v12 users.

Trying to fix this properly seems like too much effort when there are so many other places someone can break Bangle.js if they're inclined to deliberately do bad things.

The best fix for this would be tweaking the actual run app so you *could* have two boxes the same and both would update, but I think this is super low priority.
