### ISSUE TITLE
[IDEA] Support for menu separators

### ISSUE THREAD

**Issue by alessandrococco** [espruino/BangleApps#1775]
In more complex menus I'd like to separate a group of items from another (see screenshot)

![image](https://user-images.githubusercontent.com/2331798/165952400-c4bf7b3f-96bf-4063-b091-2c377d51d3ab.png)

Some ideas:
- draw a line
- more margin
- ???

Maybe we can also support an optional title?

![image](https://user-images.githubusercontent.com/2331798/165954156-ddec4450-27b0-4daa-a6c6-3972e8e30d3a.png)

What do you think?

**Comment by storm64** [comment]
This is a really nice idea.

For now I just used entries with no actions and leading `-- `, e.g. see lightswitch:

<details> 
  <summary>Screenshot:</summary>

  ![lightswitch_settings](https://user-images.githubusercontent.com/7493120/165975980-6c57f1c7-c5fa-475f-9e80-ff182c2f3e0f.png)
</details>

<details>
  <summary>Code snippet:</summary>

  ```
  // show main menu
  function showMain() {
    var mainMenu = E.showMenu({
      "": {
        title: "Light Switch"
      },
      "< Back": () => back(),
      "-- Widget": 0,
      "Bulb col": getEntry("colors"),
      "Image": getEntry("image"),
      "-- Control": 0,
      "Touch": getEntry("touchOn"),
      "Oversize": getEntry("oversize"),
      "Drag Delay": getEntry("dragDelay"),
      "Min Value": getEntry("minValue"),
      "-- Unlock": 0,
      "TapSide": getEntry("unlockSide"),
      "-- Flash": 0,
      "TapSide ": getEntry("tapSide"),
      "Tap": getEntry("tapOn"),
      "Timeout": getEntry("tOut"),
      "Min Value ": getEntry("minFlash")
    });
  }
  ```
</details>

I would like to have a separator that draws a horizontal line if no title is given and otherwise the centered title with two separated horizontal lines on each side:
`-------------`
`--- Title ---`

I just had some rough ideas for the code structure:
1. The separator is identified by a leading `"-- "`
2. Add more tailing spaces (e.g.: `"--  "`, `"--   "`) for multiple separators without a name
3. Separators with a title are written as `"-- Title"`
4. The displaying of a separator could be done quiet similar to a normal entry with less height and no or a different background

**Comment by gfwilliams** [comment]
I think if you've got a massive scrollable menu like this, it's a sign that you should be using submenus instead? 

There was a big discussion about the built-in settings app culminating in it being refactored into a bunch of nested menus, and it seems like the better option here - having to scroll down loads to get to what you want just seems like a bad user experience. If it's a section of a menu that could do with its own heading, I think it should just be in its own menu?

Also the way showScroller works right now, it doesn't support menu items of variable heights, so actually implementing this would end up being a complete pain.

**Comment by alessandrococco** [comment]
Hi @gfwilliams, thank you for your answer.

> If it's a section of a menu that could do with its own heading, I think it should just be in its own menu?

Yes, you're right.

I could refactor the Alarms app like this:

```
New Alarm >
New Timer > 
Alarms > (show list of alarms)
Timers > (show list of timers)
Bulk Actions > (enable/disable/delete all)
Settings > (open scheduler settings)
```

**Comment by gfwilliams** [comment]
* `Bulk actions` - yes, definitely. You could maybe even just make it `Utils` and hide `Settings` under that too?
* `New Alarm/Timer` could even just be `New` with a menu that pops up with the 2 options.

I'm not sure about hiding the alarms behind a menu though? It seems that's something folks might actually want to see at a glance. I think your case of having 5 alarms per day probably isn't what most people will do?

**Comment by thyttan** [comment]
Candidate for being closed - leave a comment if you object!

Rationale:
It seems as thought the discussion landed in submenus should be used instead of menu separators. From that conclusion I think this issue can be closed as not planned.

@alessandrococco went on to implement UI changes to Alarms & Timers.

**Comment by gfwilliams** [comment]
Thanks - yes, I think this can go too.
