### ISSUE TITLE
[app/ - any custom.html - ] incompatible interface.js and customize.js

### ISSUE THREAD

**Issue by Rarder44** [espruino/BangleApps#1879]
### Affected hardware version

Bangle 1, Bangle 2

### Your firmware version

2v13

### The bug

###Describe the bug 
using the two libraries interface.js and customize.js in the same html file, there is a problem related to the duplication of some variables.

###Expected behavior
that the libraries worked together (or were merged / one of the two is removed)

**Comment by gfwilliams** [comment]
Thanks - but this is expected. I didn't see this and already wrote in the PR: https://github.com/espruino/BangleApps/pull/1878

--- 

It's because interface.js is for interface.html files and customize.js is for custom.html files. You definitely shouldn't use one for the other type of app because it's entirely likely it'll break - if not now, in the future. I guess we should really add some kind of check in there to stop it.

If you need something maybe we can make sure it gets added to customize.js though.
