### ISSUE TITLE
[messages] overlapping lines when using unicode

### ISSUE THREAD

**Issue by idavydov** [espruino/BangleApps#2057]
### Affected hardware version

Bangle 2

### Your firmware version

2v14

### The bug

Overlapping lines in notification from gadgetbridge

 
![PXL_20220715_160414511](https://user-images.githubusercontent.com/671660/180480946-971ab766-f37f-4305-859a-4592970010c8.jpg)

When I receive notification from signal (in groups) sometimes lines of unicode text are partially overlapping on the screen.

I suppose the reason is that the notification header contains: "Group name: Group member", which occupies two lines. And all the subsequent lines are then partially overlapping. 

I was not able to reproduce it using gadgetbridge debug, since there you can only set a message, not the header.

I'm not sure if it's a bug in messages or in the gadgetbridge (bangle.js flavor).

**Comment by gfwilliams** [comment]
Thanks - this is a tricky one to fix. The unicode can't be displayed natively by Bangle.js so it's being converted to an image on the phone.

The Bangle *thinks* it has chosen a smaller font, but because the text is now and image the font size can't be changed and it overlaps.

If we just changed it so the background of the text wasn't cleared, would that fix it for you?

**Comment by idavydov** [comment]
Thanks, I'm not sure I understand the whole complexity of the issue.

So what you are suggesting is basically, replace "white" with "transparent" in the fond and hope that characters will not overlap?

I suppose it's better than just overwriting with "white", but still characters will overlap in some cases.

A few questions since I do not know how gadgetbridge interacts with messages.

Is there a reason why messages doesn't know the line height?

Or maybe there is a possibility to:
a) set a smaller font in gadgetbridge by default, e.g., as an option? I could then set "always use minimal font" in gadgetbridge to avoid the isse
b) let gadgetbridge (roughly) deduce the desired font size based on the text length

**Comment by gfwilliams** [comment]
> replace "white" with "transparent" in the fond and hope that characters will not overlap?

Yes - it's an easy tweak that shouldn't really break anything.

> Is there a reason why messages doesn't know the line height?

It works out the height based on the font - but since it's an image (inside the text) the height isn't related to the font.

> I could then set "always use minimal font" in gadgetbridge to avoid the isse

Yes, we could have a font size option - that could be added pretty easily

> let gadgetbridge (roughly) deduce the desired font size based on the text length

Yes, it's possible - but also very likely it'll get it wrong!

Another option is to allow Bangle.js to automatically halve the size of images in text if they are too big (or double them if they are too big). which could work well too

**Comment by gfwilliams** [comment]
I've just implemented the size config (and transparent background) - and it should roll out to the google play store in the next day or so

**Comment by idavydov** [comment]
Thanks, @gfwilliams 
I can confirm that we reduced font size + transparent background it looks much better!

**Comment by gfwilliams** [comment]
Great! Thanks for the update!
