### ISSUE TITLE
Settings: running out of memory

### ISSUE THREAD

**Issue by rigrig** [espruino/BangleApps#206]
Repeatedly opening a submenu and going back eats up memory, until there isn't enough left.

#### Steps to reproduce:
1. Open Settings
2. Select "Locale"
3. Select "< Back"
4. Repeat from 2.

##### Expected behavior:
Infinite back-and-forth through the submenus

##### Actual behavior:
After a few times "weird" things start happening, and `New interpreter error: LOW_MEMORY,MEMORY` shows up in the console.

My guess is this happens because every time you open "Locale" we create another locale menu, and every time you go "< Back" a new main menu is created, but the old menus are also still around?

Log of me typing in what I am about to select, and checking memory after selecting it:
```js
>//Settings
=undefined
>
 ____                 _
|  __|___ ___ ___ _ _|_|___ ___
|  __|_ -| . |  _| | | |   | . |
|____|___|  _|_| |___|_|_|_|___|
         |_| espruino.com
 2v05 (c) 2019 G.Williams
{"t":"status","bat":72}
>process.memory()
={ free: 1034, usage: 1066, total: 2100, history: 0,
  gc: 0, gctime: 5.40161132812, blocksize: 16, "stackEndAddress": 536923400, flash_start: 0,
  "flash_binary_end": 483740, "flash_code_start": 1073741824, flash_length: 524288 }
>//Locale
=undefined
>process.memory()
={ free: 901, usage: 1199, total: 2100, history: 6,
  gc: 0, gctime: 5.79833984375, blocksize: 16, "stackEndAddress": 536923400, flash_start: 0,
  "flash_binary_end": 483740, "flash_code_start": 1073741824, flash_length: 524288 }
>//Back
=undefined
>process.memory()
={ free: 599, usage: 1501, total: 2100, history: 8,
  gc: 0, gctime: 6.56127929687, blocksize: 16, "stackEndAddress": 536923400, flash_start: 0,
  "flash_binary_end": 483740, "flash_code_start": 1073741824, flash_length: 524288 }
>//Locale
=undefined
>process.memory()
={ free: 483, usage: 1617, total: 2100, history: 8,
  gc: 0, gctime: 6.89697265625, blocksize: 16, "stackEndAddress": 536923400, flash_start: 0,
  "flash_binary_end": 483740, "flash_code_start": 1073741824, flash_length: 524288 }
>//Back
=undefined
>process.memory()
={ free: 187, usage: 1913, total: 2100, history: 8,
  gc: 0, gctime: 7.8125, blocksize: 16, "stackEndAddress": 536923400, flash_start: 0,
  "flash_binary_end": 483740, "flash_code_start": 1073741824, flash_length: 524288 }
>//Locale
=undefined
Execution Interrupted during event processing.
New interpreter error: LOW_MEMORY,MEMORY
```

**Comment by gfwilliams** [comment]
I missed your last post  - the menu shouldn't stay around.

You create it and use `E.showMenu`, but once you use `E.showMenu` for another menu, there should be no references to the initial menu so it should be automatically garbage collected...

**Comment by rigrig** [comment]
Oh right, that makes sense

**Comment by ps-igel** [comment]
> As far as I can tell it's something to do with the scopes kept by the watches...

I really really have no great knowledge of JS in particular, but mentioning the scopes I remembered when I started coding for the Bangle having difficulties with the `this` not being what I thought it was. I think it was Gordon in the forum who pointed out the using `()=>`  kept the scope?

So I tried this using the example above and it seems to magically work?

`function showMainMenu() {
  print(process.memory().usage);
  var m1;
  const mainmenu = {
    '': { 'title': 'Settings' },
    'Locale': ()=>showLocaleMenu(),
  };
  return E.showMenu(mainmenu);
}

function showLocaleMenu() {
  var m2;
  const localemenu = {
    '': { 'title': 'Locale' },
    '< Back': ()=>showMainMenu(),
  };
  return E.showMenu(localemenu);
}

showMainMenu();`

At least the emulator now prints a constant usage of 399 bytes instead of rising numbers. Didn't test it on the Bangle itself though.

**Comment by gfwilliams** [comment]
Wow, that's great - thanks for trying this out! 

So just to be clear, all you did was change `showMainMenu` to `()=>showMainMenu()` (and the same for others?).

I think this just helped me realise what the issue might be! When the function gets called, it gets passed a reference to the current menu as an argument: https://github.com/espruino/EspruinoDocs/blob/master/modules/graphical_menu.js#L74

That means that if you define a new menu (with functions) in the function that's called, any function in there still has a reference to `arguments` (because of the scope), which is a reference to the old menu, which then keeps everything around.

Nice, easy fix. And it's not an Espruino bug either :)

**Comment by gfwilliams** [comment]
Thanks @ps-igel - just tweaked settings as you suggested and the memory usage issue is gone!
