### ISSUE TITLE
[Layout] Layout's lazy mode doesn't clear the screen

### ISSUE THREAD

**Issue by rockybulwinkle** [espruino/BangleApps#2668]
### Affected hardware version

Bangle 2

### Your firmware version

2v17

### The bug

When I use the Layout module, with lazy set to true, it does not properly clear modified fields.

Here is example code that shows the behavior, modified from the Layout tutorial:
```var Layout = require("Layout");
var layout = new Layout({
  type: "v",
  c: [{
    type: "txt",
    font: "20%",
    label: "",
    id: "count"
  }, ]
}, {
  lazy: true
});

// timeout used to update every second
var drawTimeout;

// number to show on screen
var count = 9;

// update the screen
function draw() {
  var d = new Date();
  // update time and date
  layout.count.label = count;
  count += 1;
  layout.render();
  // schedule a draw for the next minute
  if (drawTimeout) clearTimeout(drawTimeout);
  drawTimeout = setTimeout(function() {
    drawTimeout = undefined;
    draw();
  }, 1000);
}

// update time and draw
g.clear();
draw();
```

Within 2 updates, when it transitions from display 9->10->11, the bug appears:

<img src="https://user-images.githubusercontent.com/833778/228905759-b6a13b08-6965-473f-82fe-bb6eedce23ab.png" width=20% height=20%>

It gets worse over time:

<img src="https://user-images.githubusercontent.com/833778/228905728-ed01dd30-20d0-42bc-900b-c1b32ed44f57.png" width=20% height=20%>

Am I missing something here about how lazy mode is supposed to be used?

**Comment by rockybulwinkle** [comment]
I see some apps are using Layout's update method, but this isn't talked about in the Layout tutorial.

**Comment by gfwilliams** [comment]
Ahh - so I think the issue is that layout wants to lay out everything on the screen and figure out how much space to allocate to each thing. In the examples on http://www.espruino.com/Bangle.js+Layout we pre-populate the layout with placeholder strings, which are basically the maximum size we expect things to be.

But then (and we don't do this in the examples) we need to let Layout actually lay everything out - either by rendering with .render, or by just calling .update (which lays out but doesn't render).

Then when you just change the label and render, it's that area which gets cleared.

So for example something like this should work:

```
var Layout = require("Layout");
var layout = new Layout({
  type: "v",
  c: [{
    type: "txt",
    font: "20%",
    label: "----",
    id: "count"
  }, ]
}, {
  lazy: true
});
layout.update();
```

The issue in your code is that the first thing you do is set the label to `9` and then render, so layout assumes the size of the area is all that's needed to render a `9`, and that's all it clears.

I'll update the docs

**Comment by rockybulwinkle** [comment]
A font I'm using has variable width. I assume when you say maximum width, that is the maximum pixel width, not maximum character width?

**Comment by gfwilliams** [comment]
Yes, it's the maximum space on the screen you think text will take up.

In the docs I'd added at https://github.com/espruino/EspruinoDocs/commit/8d4b022f52c03693c09ce95f302dbfddef80fc13 I mention that you can just use `fillx:1` to make the area stretch across the whole screen, which would fix this without you needing a placeholder
