### ISSUE TITLE
E.showMenu() fails with special character on firmware 2v19

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#3033]
The following snippet which should show a menu entry with a german umlaut
```
E.showMenu({"Hello \u00E4": undefined});
```
worked with firmware 2v18:
![Download](https://github.com/espruino/BangleApps/assets/885742/a900e7c3-bd43-4e8f-9377-dd3f7438482d)

But fails with firmware 2v19 (up to 2v19.21):
> Uncaught Error: Expecting first argument to a valid Image
 at line 2 col 337
...r[a];k=g.wrapString(a,b.w-l);1<k.length&&(k=g.setFont("6x15"...
                              ^
in function "draw" called from line 1 col 142
...,{x:a.x,y:m(b),w:a.w,h:d.h});g.setClipRect(0,0,g.getWidth()-...
                              ^
in function "draw" called from line 3 col 339
...w==n},f=e.scroll&-2;e.draw();g.flip();return e
                              ^
in function called from line 1 col 28
p.scroller=E.showScroller(u)
                           ^
at line 1 col 28
p.scroller=E.showScroller(u)
                           ^
in function "t" called from line 8 col 247
....scroller.drawItem(a)}}};t();return p
                              ^
in function called from line 1 col 20
E.showMenu(mainMenu);
![Download](https://github.com/espruino/BangleApps/assets/885742/08ac02ea-dbe0-4770-95e1-1b7ec735d5b5)

**Comment by thyttan** [comment]
Possibly related: I haven't tried to pin it down, but semi-recently messages started showing with missing sections for me. I enabled "Text as Bitmaps" in Gadgetbridge and that seemed to fix my issue. But I'm almost certain I didn't need this setting toggled on to receive complete messages before.

**Comment by gfwilliams** [comment]
Ok, thanks - if you need to work around it, this works fine: `E.showMenu({"Hello \xE4": undefined});`

How did this one come up? I thought usually we convert characters that are in the UTF8 code range into the `\x..` form now.

The issue appears to be to do with how UTF8 strings are stored when they're object keys - for compatibility we treat `\xE4` as a non-UTF8 string.

```
>trace({'Hello \u00e4': undefined})
#1403[r0,l1] Object {
  #1324[r1,l2] Name String [2 blocks] "\0\0\0\0o \xC3\xA4"    undefined
}
```

This one could end up being a bit of a pain to sort out since the way we tag strings as being UTF8 isn't really compatible with this. I'll have to have a think how we work around it.

And yes, since we added UTF8 support in Bangle.js, we went through a stage where Gadgetbridge was still sending UTF8 chars (like 0xE4) but Bangle.js had to interpret them as UTF8 (but it was invalid) - but I thought we'd got that fixed now - Gadgetbridge shouldn't be sending those chars and also Bangle.js should treat invalid unicode as normal non-UTF8 data

**Comment by gfwilliams** [comment]
Just a note that this is hopefully fixed with https://github.com/espruino/Espruino/commit/dde4d3a5ca52782fbe7cefacb18d52d9655b485a now - but I'll need to do a bit more testing

**Comment by nxdefiant** [comment]
Cool thx, I'll fetch the cutting edge build.

The original bug was seen in [noteify](https://banglejs.com/apps/?id=noteify), a text with a special character was entered from the webinterface, save as json on the device and shown in the app.

**Comment by gfwilliams** [comment]
Ok, just checked on a Bangle and this now all seems work work fine - phew!

UTF8 always seems to end up being a bit of a nightmare, and we're not really seeing any of the benefits at the moment. Hopefully soon though :)
