### ISSUE TITLE
[app/widget name] HR x10 

### ISSUE THREAD

**Issue by 4o4R** [espruino/BangleApps#3610]
### Affected hardware version

Bangle 2

### Your firmware version

2v14

### The bug

Clock_info returns heart rate 10x too high. 
On my Bangle.Js2 using the LCD face, the clock_info app is returning my HR x10, so that a 72 pulse is showing as 721pm. Is there a round error? I was going to brute force /10 but figured best to raise the issue for a fix instead. Thank you!

### Installed apps

https://banglejs.com/apps/?id=lcdclock
Clock Info Module (v0.12)

**Comment by bobrippling** [comment]
I wonder if this is some hardware quirk - @gfwilliams have you seen this before?

**Comment by gfwilliams** [comment]
I haven't seen it, no.  Please can you post a screenshot? The app loader can make one under `more...`

First thought though is LCD clock uses kind of a hard to read font.

The actual text sent would be `72 bpm` which gets converted to `72BPM` and I notice you write `721pm`

And I'm just wondering if maybe you're reading the `B` as an `8` -> `728PM` because actually on a 7 segment display they would be the same?
