### ISSUE TITLE
App sorting by new error

### ISSUE THREAD

**Issue by v1nc** [espruino/BangleApps#497]
I noticed an error in app sorting by new. 

For example, the  app "Magic 8Ball" https://github.com/espruino/BangleApps/pull/421 was merged 26 days ago, but is listed at the bottom of the page. 

I could not spot the reason for this yet.

**Comment by gfwilliams** [comment]
The dates are generated from the first commit on Github.

I just checked and it's working as expected... If you enter this in the console, you can see the dates:

```
visibleApps = appJSON.slice()
activeSort = "created"
visibleApps.sort((a,b) => appSortInfo[b.id][activeSort] - appSortInfo[a.id][activeSort]);
visibleApps.forEach(a=>console.log(a.id, new Date(appSortInfo[a.id][activeSort])))
// prints...
VM430:1 notifyfs Thu Jun 04 2020 16:18:41 GMT+0100 (British Summer Time)
VM430:1 notify Thu Jun 04 2020 14:28:44 GMT+0100 (British Summer Time)
VM430:1 analogimgclk Thu Jun 04 2020 10:21:02 GMT+0100 (British Summer Time)
VM430:1 life Wed Jun 03 2020 17:19:02 GMT+0100 (British Summer Time)
VM430:1 animclk Thu May 28 2020 14:36:54 GMT+0100 (British Summer Time)
VM430:1 sleepphasealarm Wed May 27 2020 06:50:48 GMT+0100 (British Summer Time)
VM430:1 verticalface Wed May 27 2020 04:58:47 GMT+0100 (British Summer Time)
VM430:1 binclock Sun May 24 2020 21:27:04 GMT+0100 (British Summer Time)
VM430:1 pizzatimer Sat May 23 2020 16:31:48 GMT+0100 (British Summer Time)
...
VM430:1 jbm8b Tue Feb 04 2020 21:47:28 GMT+0000 (Greenwich Mean Time)
```

Magic 8 ball was created on 4th Feb, so ends up nearer the bottom: https://github.com/espruino/BangleApps/commits/master/apps/jbm8b

Unfortunately because the times come from Git it's when the app was created first, not when it was published. It's not ideal but it's better than nothing.
