### ISSUE TITLE
Graphics API changes

### ISSUE THREAD

**Issue by gfwilliams** [espruino/BangleApps#582]
There are a few things I'm not happy with right now:

- [x] We reserve 24px of space at the top of the screen for widgets, however it'd be nice to allow a thin widget bar for those that care (slideable widgets and Bangle.appRect - see below)
- [x] If there are no widgets at the bottom it'd be nice to ensure apps could easily tell and use the extra space
- [x] It'd be nice to allow a global color theme, covered in https://github.com/espruino/BangleApps/issues/499
- [x] there's no way to request an app redraws everything (eg maybe we displayed a notification and lost what was on screen). **There is now `Bangle.setUI({mode:"custom",redraw:...})` ** but this isn't used widely (if at all!) yet
- [ ] I think Bangle.setLCDMode for all but double buffering should be removed, and standard `Graphics.drawImage` with an offscreen buffer should be used instead as it's way more flexible.

Any thoughts about these?

* I guess we could have `g.clientArea => {x,y,w,h}` which we updated when drawing widgets *and* the app, so then apps/widgets would have a clear idea what area they were expecting to redraw?
* `g.theme.bg/fg/bg2/fg2` for the theme? Ideally `g.reset()` would be aware of this and would set BG and FG automatically.
* Maybe a `Bangle.on('redraw'` event apps could hook onto? Notifications could also check to see if the event was implemented before trashing the screen

**Comment by rigrig** [comment]
Wouldn't having a thin widget bar also mean that all widgets need to check their height, and then fit themselves into whatever space there is?

`g.theme.` sounds nice, what would you use `bg2` for though? Maybe just have one `bg` and `fg1`,`fg2`,`fg3`?
I'm not too sure about changing `g.reset()`, it wouldn't surprise me if there are apps doing `g.reset().setColor(-1)`, and they only show up as broken for people with black-on-white themes.

`Bangle.on('redraw')` seems nice, although I'm not too sure how useful it will actually be: notifications can't really trash the screen anyway, because the clock might draw over it every second. Unless there is some way to stop other apps from drawing?

**Comment by gfwilliams** [comment]
> Wouldn't having a thin widget bar also mean that all widgets need to check their height

Yes - although in many cases the change would be pretty simple. It's actually more for targeting different watches/devices that have different screen resolutions - 24px is a bit large on some of them.

> what would you use bg2 for though?

Imagine a menu where you have a highlighted entry. You want a different foreground but also a different background.

> it wouldn't surprise me if there are apps doing g.reset().setColor(-1), and they only show up as broken for people with black-on-white themes.

True, but not doing that means you definitely have to change *all* apps/widgets. The plus side I guess is it could be implemented in a backwards-compatible way.

> Bangle.on('redraw')

> Unless there is some way to stop other apps from drawing?

Yes - you can do clipRect or 'setLCDMode("null")`. The current notifications scroll the screen and use a different area of the screen buffer.

The other benefit of this is you could actually get a proper screenshot capability - by having a small (240 x 24 x 16?) buffer and then repeatedly calling `Bangle.emit('redraw')` you could get a full image of the screen back to the PC (albeit slowly!)

**Comment by rigrig** [comment]
I guess it would be nice if widgets could scale. Its just that I expect getting all widgets to play nice with a variable drawing area to be a lot of effort.

> You want a different foreground but also a different background.

Right, that makes sense.
I was thinking more along the lines of having different colors, e.g. you would draw most things in `fg1`, but maybe add some elements in `fg2` so it isn't all monochrome. But I don't think many apps use two colors now anyway, so that might be a bit overkill.

>> it wouldn't surprise me if there are apps doing g.reset().setColor(-1)

On reflection, this probably won't be much of a problem, as we will searching to change every `setColor(-1)` anyway. And needing to call `.setColor(g.fg).setBgColor(g.bg)` after every reset actually doesn't sound all that great.

**Comment by gfwilliams** [comment]
We now have `Bangle.appRect` - it's just getting apps to use this

**Comment by gfwilliams** [comment]
Thanks! Yes, I think that makes sense.

The one remaining one I see is the `redraw` option - and it strikes me that we could add that to `Bangle.setUI` pretty easily?

Also it's not such a big deal as we have overlays now

**Comment by gfwilliams** [comment]
Closing this - we now have `redraw` and while setLCDMode is still there it's not really used
