### ISSUE TITLE
Reset via BTN3 causes error messages

### ISSUE THREAD

**Issue by MaBecker** [espruino/BangleApps#59]
Looks like bootloader loads the clock app before loading  widgets.

Output:
 
Uncaught ReferenceError: "widget" is not defined
 at line 1 col 30
eval(require("Storage").read(widget))
                             ^
in function called from line 127 col 103
...re("Storage").read(widget)));
`

Switching to menu and back does not cause errors and widgets are loaded properly.

Any hints how to fix it?

Is this the expected load order?
* setting
* widgets
* clock if available

**Comment by MaBecker** [comment]
>require('Storage').list();
=[
  ".bootcde",
  "+setting",
  "-setting",
  "=setting",
  "*setting",
  "+sbt",
  "=sbt",
  "+sbat",
  "=sbat",
  "+miclock",
  "-miclock",
  "*miclock",
  "@setting"
 ]
>

**Comment by gfwilliams** [comment]
> `"@ setting" <-- added space`

That's extremely strange. It doesn't even seem possible since filenames are only 8 characters!

It's expected that the bootloader loads the clock before widgets, yes (and the settings app is in fact a widget) - there's another open issue at the moment (and you also spotted) the way timezone doesn't update immediately.

However, I assume the error comes from this line:

```
require("Storage").list().filter(a=>a[0]=='=').forEach(widget=>eval(require("Storage").read(widget)));
```

Since it's the only thing in the app store containing `eval(require("Storage").read(widget))` - and I just don't see how that can create the error, because it's a function with `widget` as an argument!

**Comment by MaBecker** [comment]
Sorry, I added that space so it is not decode. as GitHub user

**Comment by MaBecker** [comment]
Ok, started from scratch and loaded bootloader, widgets and apps with firmware.js technic.

**Comment by gfwilliams** [comment]
and it works fine?

**Comment by MaBecker** [comment]
Yes, every thing works fine with the new bootloader version.
