### ISSUE TITLE
Feature Request: Filter By Compatible Device (Bangle.js 1 and/or 2)

### ISSUE THREAD

**Issue by hasmar04** [espruino/BangleApps#852]
As apps are starting to be made for individual models or both, the ability to filter by apps that have been tested and tagged as bangle.js 2 and/or 1 compatible would be a useful feature of the web loader. 
This could be implemented through the addition of a 'tags' or 'info' file for each app.

**Comment by hasmar04** [comment]
Just discovered this functionality already exists within apps.json

**Comment by gfwilliams** [comment]
> is there a reason that the apps.json cannot be split into each apps folder?

Yes - it's because we're trying to allow the site to be served statically from GitHub pages so it's easy for everyone to clone and try out their app with.

GitHub pages doesn't allow directory indexing so we couldn't automatically find each app, but even if we could, firing off 250+ HTTP requests when the page was loaded would probably really hurt performance :(
