### ISSUE TITLE
12 hr clock setting doesn't work

### ISSUE THREAD

**Issue by eyecreate** [espruino/BangleApps#892]
I changed my locale to en_US and went to locale menu and changed clock to 12hr. Anton clock should be able to handle since it asks locale module for time, but it still shows up as 24hr time.

**Comment by gfwilliams** [comment]
Thanks - I'll check on that. Hopefully it's just an update to the locale module

**Comment by jg76379** [comment]
I took a look at the locales module and it doesn't looks like it is reading setting.json to get the 12 hour time setting. 

It seems like it should be doing something like the following to get the setting:

```
const storage = require('Storage');
var settings = storage.readJSON('setting.json', 1);
var time12Hr = settings['12hour'];
```

And then modifying the time format, but i'm not sure how to implement this because of the way that the locale module is setup. Since that code within `locale.html` is running in the browser to generate the actual locale code that is sent to the device.  Where would you check the settings to adjust the time format?

**Comment by Izaic** [comment]
Hopefully it's an easy fix

**Comment by JayAndCatchFire** [comment]
This seems to still be an issue.  Maybe because the build failed?

**Comment by eyecreate** [comment]
I'm running build 2v10.234 and it's working. Are you running a different build or have you tried a factory reset?

**Comment by JayAndCatchFire** [comment]
Ah, good call.  I'm on 2v10.219.  I didn't realize this update required a firmware update.

**Comment by JayAndCatchFire** [comment]
After I updated the firmware, it works as expected.  Thank you!
